SET SERVEROUTPUT ON;
INSERT INTO ZONARESIDENCIAS(OID_Z,NOMBREZONA,PROVINCIA) VALUES (SEC_ZONARESIDENCIAS.NEXTVAL,'TRIANA','SEVILLA');
INSERT INTO USUARIOS(OID_U,NOMBRE,APELLIDOS,EMAIL,TELEFONO,SEXO,OID_Z) VALUES(SEC_USUARIOS.NEXTVAL,'Alejandro','García Vera','aleg@gmail.com',638683810,'Hombre',SEC_ZONARESIDENCIAS.CURRVAL);
DECLARE

 oid_T NUMBER;
    
  BEGIN
 
  PRUEBAS_TUTORES.INICIALIZAR;
    OID_T := sec_usuarios.currval;
  PRUEBAS_TUTORES.INSERTAR ('Prueba 1 - Inserción tutores',OID_T,true);
  PRUEBAS_TUTORES.INSERTAR ('Prueba 2 - Inserción tutores null',NULL,false);
   PRUEBAS_TUTORES.ELIMINAR('Prueba 5 - Eliminar tutores', OID_T, true);
    
  END;