SET SERVEROUTPUT ON;
INSERT INTO ZONARESIDENCIAS(OID_Z,NOMBREZONA,PROVINCIA) VALUES (SEC_ZONARESIDENCIAS.NEXTVAL,'TRIANA','SEVILLA');
INSERT INTO USUARIOS(OID_U,NOMBRE,APELLIDOS,EMAIL,TELEFONO,SEXO,OID_Z) VALUES(SEC_USUARIOS.NEXTVAL,'Alejandr','García Vera','aleg@gmail.com',638683810,'Hombre',SEC_ZONARESIDENCIAS.CURRVAL);
INSERT INTO MODALIDADES(OID_M,NOMBRE) VALUES (SEC_MODALIDADES.NEXTVAL,'PAJERO PROFESIONA');
DECLARE

 oid_p NUMBER;
 OID_M NUMBER;
    
  BEGIN
   
  PRUEBAS_PROFESORES.INICIALIZAR;
  oid_p := sec_usuarios.currval;
  OID_M := SEC_MODALIDADES.CURRVAL;
  PRUEBAS_PROFESORES.INSERTAR ('Prueba 1 - Inserción profesor',OID_P,2,true);
  PRUEBAS_PROFESORES.INSERTAR ('Prueba 2 - Inserción prof null',NULL, null,false);
  PRUEBAS_PROFESORES.ACTUALIZAR('Prueba 3 - Actualización prof', oid_p, OID_M,true);
  PRUEBAS_PROFESORES.ACTUALIZAR('Prueba 4 - Actualización prof null', OID_p,23,false);
  PRUEBAS_PROFESORES.ELIMINAR('Prueba 5 - Eliminar prof', OID_p, true);
    
  END;