
      DROP TABLE Usuarios CASCADE CONSTRAINTS;
      DROP TABLE Tutores CASCADE CONSTRAINTS;
      DROP TABLE Alumnos CASCADE CONSTRAINTS;
      DROP TABLE Modalidad CASCADE CONSTRAINTS;
      DROP TABLE EsHijoDe CASCADE CONSTRAINTS;
      DROP TABLE Matriculas CASCADE CONSTRAINTS;
      DROP TABLE Facturas CASCADE CONSTRAINTS;
      DROP TABLE Asignaturas CASCADE CONSTRAINTS;
      DROP TABLE Profesores CASCADE CONSTRAINTS;
      DROP TABLE Salarios CASCADE CONSTRAINTS;
      DROP TABLE Valoraciones CASCADE CONSTRAINTS;
      DROP TABLE ZonaResidencias CASCADE CONSTRAINTS;
      DROP TABLE Modalidades CASCADE CONSTRAINTS;
      