create or replace function obtenerEdad(FECHANACIMIENTO IN ALUMNOS.FECHANACIMIENTO%TYPE)
 RETURN NUMBER 
 IS 
 EDAD  ALUMNOS.EDAD%TYPE;
 
 BEGIN
     
     EDAD:= TRUNC(MONTHS_BETWEEN(SYSDATE, 
      FECHANACIMIENTO) / 12, 0);
      
RETURN(EDAD);

END obtenerEdad;