create or replace PROCEDURE ACTUALIZA_ALUMNOS(
  
            w_OID_A IN Alumnos.OID_A%TYPE,
            
            w_Escuela IN Alumnos.Escuela%Type,
            
            w_Edad IN Alumnos.Edad%TYPE
)
IS
BEGIN
  UPDATE ALUMNOS SET EDAD = w_Edad WHERE w_OID_A = OID_A;
  UPDATE ALUMNOS SET ESCUELA = w_Escuela WHERE w_OID_A = OID_A;

END ACTUALIZA_ALUMNOS;
/
CREATE OR REPLACE PROCEDURE ACTUALIZA_USUARIOS(

        w_OID_U  IN    Usuarios.OID_U%TYPE,
        w_Email IN Usuarios.Email%TYPE,
        w_OID_Z IN Usuarios.OID_Z%TYPE,
        w_Telefono IN Usuarios.Telefono%TYPE
)

IS

BEGIN
      UPDATE  USUARIOS SET EMAIL = w_Email WHERE w_OID_U = OID_U;
      UPDATE  USUARIOS SET OID_Z = w_OID_Z WHERE w_OID_U = OID_U;
      UPDATE  USUARIOS SET TELEFONO = w_Telefono WHERE w_OID_U = OID_U;
END ACTUALIZA_USUARIOS;
/
CREATE OR REPLACE PROCEDURE ACTUALIZA_ASIGNATURAS(

        W_OID_ASIG IN ASIGNATURAS.OID_ASIG%TYPE,
        W_Nombre IN ASIGNATURAS.CURSO%TYPE
)
IS
BEGIN
UPDATE ASIGNATURAS SET Nombre = W_Nombre WHERE W_OID_ASIG = OID_ASIG;
END ACTUALIZA_ASIGNATURAS;
/
CREATE OR REPLACE PROCEDURE ACTUALIZA_FACTURAS(
  
    W_OID_F IN FACTURAS.OID_F%TYPE,
    W_FECHADEPAGO IN FACTURAS.FECHADEPAGO%TYPE,
    W_PAGADO IN FACTURAS.PAGADO%TYPE

)
IS
BEGIN
UPDATE FACTURAS SET FECHADEPAGO = W_FECHADEPAGO WHERE W_OID_F = OID_F;
UPDATE FACTURAS SET PAGADO = W_PAGADO WHERE W_OID_F = OID_F;
END ACTUALIZA_FACTURAS;
/
CREATE OR REPLACE PROCEDURE ACTUALIZA_MATRICULAS(
  
    W_OID_MAT IN MATRICULAS.OID_MAT%TYPE,
    W_EVALUACION IN MATRICULAS.EVALUACION%TYPE

)
IS
BEGIN
UPDATE MATRICULAS SET EVALUACION = W_EVALUACION WHERE W_OID_MAT = OID_MAT;

END ACTUALIZA_MATRICULAS;
/
CREATE OR REPLACE PROCEDURE ACTUALIZA_SALARIOS(
  
    W_OID_S IN SALARIOS.OID_S%TYPE,
    W_SALARIO_MES IN SALARIOS.SALARIO_MES%TYPE,
    W_MES IN SALARIOS.MES%TYPE
   

)
IS
BEGIN
UPDATE SALARIOS SET SALARIO_MES = W_SALARIO_MES WHERE W_OID_S = OID_S;
UPDATE SALARIOS SET MES = W_MES WHERE W_OID_S = OID_S;

END ACTUALIZA_SALARIOS;
/
CREATE OR REPLACE PROCEDURE ACTUALIZA_ZONARESIDENCIAS(

  W_OID_Z IN ZONARESIDENCIAS.OID_Z%TYPE,
  W_NOMBREZONA IN ZONARESIDENCIAS.NOMBREZONA%TYPE,
  W_PROVINCIA IN ZONARESIDENCIAS.PROVINCIA%TYPE)
  IS
  BEGIN
  UPDATE ZONARESIDENCIAS SET NOMBREZONA = W_NOMBREZONA WHERE W_OID_Z = OID_Z;
  UPDATE ZONARESIDENCIAS SET PROVINCIA = W_PROVINCIA WHERE W_OID_Z = OID_Z;
  END ACTUALIZA_ZONARESIDENCIAS;